### PR TITLE
Use tmpfile() instead of generating a path with uniqid()

### PR DESCRIPTION
**Pull request by fterrag**

### CODE REVIEW

**Comment by fterrag** [comment]
@securingsincity I would appreciate your review and thoughts here. I'm worried about the use of uniqid() as PHP does not guarantee uniqueness of return value (see http://php.net/uniqid). PHP's tmpfile() uses mkstemp() or mktemp() depending on what's available. http://man7.org/linux/man-pages/man3/mkstemp.3.html

**Review by securingsincity — APPROVED** [review]
looks good. might help to have a comment about how `$meta['uri']` actually points to the filename per the docs in http://php.net/stream_get_meta_data.

**Comment by fterrag** [comment]
@securingsincity Thanks for the feedback. I added some comments around the usage of stream_get_meta_data(). Let me know what you think!

**Comment by securingsincity** [comment]
👍

**Pull request merged**
